FROM node:20-alpine/node

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY . .

RUN mkdir -p /app/data /app/uploads && chown -R node:node /app/data /app/uploads

ENV PORT=3000
EXPOSE 3000

CMD [ "node", "server.js" ]